export const AUDIT_ACTION_LABELS: Record<string, string> = {
  CREATE: "ثبت",
  UPDATE: "ویرایش",
  DELETE: "حذف",
  CANCEL: "لغو",
  RESTORE: "بازیابی",
  STATUS_CHANGE: "تغییر وضعیت",
  ENABLE: "فعال‌سازی",
  DISABLE: "غیرفعال‌سازی",
  PAYMENT_RECEIVED: "ثبت دریافت",
  PAYMENT_CANCELED: "لغو دریافت",
  EXPENSE_CREATED: "ثبت هزینه",
  EXPENSE_UPDATED: "ویرایش هزینه",
  EXPENSE_DELETED: "حذف هزینه",
  PRINT: "چاپ",
  EXPORT: "خروجی",
  BACKUP_EXPORT: "خروجی پشتیبان",
  BACKUP_REVIEW: "بازبینی پشتیبان",
  BACKUP_RESTORE: "بازیابی پشتیبان",
  BACKUP_RESTORE_FAILED: "خطای بازیابی پشتیبان",
  LOGIN: "ورود",
  SECURITY_CHANGE: "تغییر امنیتی",
  SETTINGS_UPDATE: "به‌روزرسانی تنظیمات",
  NOTIFICATION_SENT: "ارسال اعلان",
  NOTIFICATION_FAILED: "خطای اعلان",
  POST_EVENT_HELD: "تأیید برگزاری مراسم",
  POST_EVENT_NOT_HELD: "ثبت عدم برگزاری مراسم",
  POST_EVENT_INVOICE_ISSUED: "صدور صورتحساب بعد از مراسم",
  CUSTOMER_INVOICE_LINK_CREATED: "ساخت لینک مشتری صورتحساب",
  CUSTOMER_INVOICE_FEEDBACK_SUBMITTED: "ثبت نظر مشتری روی صورتحساب",
  OWNER_OPERATION_SETTING_UPDATED: "ثبت تنظیمات مالک و پیمان",
  OWNER_MONTHLY_SETTLEMENT_GENERATED: "ساخت تسویه ماهانه مالک",
  OWNER_MONTHLY_SETTLEMENT_APPROVED: "تأیید تسویه ماهانه مالک",
  OWNER_MONTHLY_SETTLEMENT_PAID: "ثبت پرداخت تسویه مالک",
  MONTHLY_CLOSE_BLOCKED_POST_EVENT_CONFIRMATION: "انسداد تعیین وضعیت مراسم در ماه بسته",
  MONTHLY_CLOSE_BLOCKED_POST_EVENT_INVOICE: "انسداد صدور صورتحساب در ماه بسته",
  MONTHLY_CLOSE_BLOCKED_INVOICE_SEND: "انسداد ارسال صورتحساب در ماه بسته",
  MONTHLY_CLOSE_BLOCKED_CUSTOMER_INVOICE_FEEDBACK: "انسداد پاسخ مشتری در ماه بسته",
  MONTHLY_CLOSE_BLOCKED_INVOICE_ADJUSTMENT_REQUEST: "انسداد درخواست اصلاح فاکتور در ماه بسته",
  MONTHLY_CLOSE_BLOCKED_INVOICE_ADJUSTMENT_APPLY: "انسداد اعمال اصلاح فاکتور در ماه بسته",
  MONTHLY_CLOSE_BLOCKED_OWNER_SETTLEMENT_REGENERATION: "انسداد بازسازی تسویه مالک در ماه بسته",
  OWNER_FINANCIAL_CONTROL_AUDIT_VIEWED: "مشاهده کنترل مالی مالک",
  INVOICE_ADJUSTMENT_REQUEST_CREATED: "ثبت درخواست اصلاح فاکتور",
  INVOICE_ADJUSTMENT_OWNER_APPLIED: "اعمال اصلاح فاکتور توسط مالک",
  INVOICE_ADJUSTMENT_OWNER_REJECTED: "رد اصلاح فاکتور توسط مالک",
  INVOICE_NOTIFICATION_DELIVERY_COMPLETED: "ارسال اعلان صورتحساب",
  INVOICE_NOTIFICATION_DELIVERY_REVIEW_REQUIRED: "خطای ارسال اعلان صورتحساب",
  OWNER_MONTHLY_SETTLEMENT_EXPORTED: "خروجی تسویه ماهانه مالک",
  OWNER_MONTHLY_SETTLEMENT_PRINT_VIEWED: "مشاهده چاپ تسویه ماهانه مالک",
  POST_EVENT_INVOICE_FINAL_HARDENING_VIEWED: "مشاهده سخت‌سازی نهایی صورتحساب بعد از مراسم",
};

export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  CONTRACT: "قرارداد",
  CUSTOMER: "مشتری",
  CALENDAR_DAY: "روز تقویم",
  PAYMENT: "دریافتی",
  RECEIPT: "دریافتی",
  EXPENSE: "هزینه",
  MENU: "منوی پذیرایی",
  SERVICE: "خدمات مراسم",
  PAYMENT_METHOD: "روش دریافت",
  FINANCIAL_CATEGORY: "دسته‌بندی مالی",
  CONTRACT_SETTING: "تنظیمات قرارداد",
  HALL_INFO: "اطلاعات تالار",
  ACCOUNT: "حساب کاربری",
  TELEGRAM_SETTING: "تنظیمات تلگرام",
  SMS_SETTING: "تنظیمات پیامک",
  NOTIFICATION_SETTING: "تنظیمات اعلان‌ها",
  MESSAGE_TEMPLATE: "قالب پیام",
  REPORT: "گزارش",
  BACKUP: "پشتیبان‌گیری",
  SECURITY: "امنیت حساب",
  SYSTEM: "سامانه",
  POST_EVENT_CONFIRMATION: "تعیین وضعیت بعد از مراسم",
  INVOICE: "صورتحساب",
  OWNER_OPERATION_SETTING: "تنظیمات مالک و پیمان",
  OWNER_FINANCIAL_AUDIT: "کنترل مالی مالک",
  OWNER_MONTHLY_SETTLEMENT: "تسویه ماهانه مالک",
  MONTHLY_CLOSE_LOCK: "قفل ماه مالی",
  INVOICE_ADJUSTMENT_REQUEST: "درخواست اصلاح فاکتور",
  POST_EVENT_INVOICE_HARDENING: "سخت‌سازی صورتحساب بعد از مراسم",
};

export const AUDIT_ACTION_OPTIONS = Object.entries(AUDIT_ACTION_LABELS).map(
  ([value, label]) => ({ value, label }),
);

export const AUDIT_ENTITY_OPTIONS = Object.entries(AUDIT_ENTITY_LABELS).map(
  ([value, label]) => ({ value, label }),
);
